[package]
name = "hisui"
version = "2025.1.0-canary.0"
edition = "2024"
authors = ["Shiguredo Inc."]
license = "Apache-2.0"
description = "Recording Composition Tool Hisui"
homepage = "https://github.com/shiguredo/hisui"
repository = "https://github.com/shiguredo/hisui"
readme = "README.md"

[features]
fdk-aac = ["shiguredo_fdk_aac"]

[dependencies]
env_logger = { version = "0.11.6", default-features = false, features = ["auto-color", "color", "humantime"] }
indicatif = "0.17.9"
libc = "0.2.171"
log = "0.4.25"
noargs = "0.2.0"
orfail = "1.1.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
shiguredo_mp4 = "2025.1.0"

shiguredo_dav1d = { version = "2025.1.0-canary.0", path = "crates/shiguredo_dav1d/" }
shiguredo_fdk_aac = { version = "2025.1.0-canary.0", path = "crates/shiguredo_fdk_aac/", optional = true }
shiguredo_libvpx = { version = "2025.1.0-canary.0", path = "crates/shiguredo_libvpx/" }
shiguredo_openh264 = { version = "2025.1.0-canary.0", path = "crates/shiguredo_openh264/" }
shiguredo_opus = { version = "2025.1.0-canary.0", path = "crates/shiguredo_opus/" }
shiguredo_svt_av1 = { version = "2025.1.0-canary.0", path = "crates/shiguredo_svt_av1/" }

[target.'cfg(target_os = "macos")'.dependencies]
shiguredo_audio_toolbox = { path = "crates/shiguredo_audio_toolbox/" }
shiguredo_video_toolbox = { path = "crates/shiguredo_video_toolbox/" }

[dev-dependencies]
tempfile = "3.18.0"

[workspace]
members = [
  "crates/shiguredo_audio_toolbox",
  "crates/shiguredo_dav1d",
  "crates/shiguredo_fdk_aac",
  "crates/shiguredo_libvpx",
  "crates/shiguredo_openh264",
  "crates/shiguredo_opus" ,
  "crates/shiguredo_svt_av1",
  "crates/shiguredo_video_toolbox"
]
