[project]
name = "hisui-plugin-examples"
version = "0.1.0"

dependencies = [
    "sora-sdk",
    "numpy",
]

requires-python = ">=3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false
