name: build-nvcodec

on:
  push:
    branches:
      - feature/gha-build-nvcodec

jobs:
  ubuntu-binary:
    name: "Upload Binary for Ubuntu"
    strategy:
      matrix:
        platform:
          - name: ubuntu-24.04_x86_64
            runs-on: ubuntu-24.04
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install packages to build external dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build nasm yasm build-essential autoconf automake libtool pkg-config yasm cmake

      # CUDA のインストール (x86_64 のみ)
      - name: Install CUDA
        if: contains(matrix.platform.name, 'x86_64')
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_*all.deb
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y install cuda-toolkit-12

      - run: rustup update stable
      - run: rustup default stable

      # x86_64 では nvcodec feature を有効化
      - name: Build with NVCODEC (x86_64)
        if: contains(matrix.platform.name, 'x86_64')
        run: cargo build --release --features nvcodec
