name: CI Windows

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "feature/**"
    paths-ignore:
      - "**.md"
      - "python/**"
      - ".github/workflows/pypi-publish.yml"

env:
  RUST_BACKTRACE: 1

jobs:
  ci-windows:
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable
      - name: Install packages to build external dependencies
        run: |
          choco install nasm -y
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          pip install meson ninja
      - name: Update PATH for nasm
        run: echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: shiguredo/github-actions/.github/actions/rust-cache@main
        with:
          os: windows-2022
          toolchain: stable
      - run: cargo fmt --all --check
      - run: cargo check --workspace --no-default-features --exclude shiguredo_fdk_aac --exclude shiguredo_openh264 --exclude shiguredo_audio_toolbox --exclude shiguredo_video_toolbox --exclude shiguredo_nvcodec --exclude shiguredo_libvpx
      - run: cargo clippy --workspace --no-default-features --exclude shiguredo_fdk_aac --exclude shiguredo_openh264 --exclude shiguredo_audio_toolbox --exclude shiguredo_video_toolbox --exclude shiguredo_nvcodec --exclude shiguredo_libvpx -- --deny warnings
      - run: cargo test --workspace --no-default-features --exclude shiguredo_fdk_aac --exclude shiguredo_openh264 --exclude shiguredo_audio_toolbox --exclude shiguredo_video_toolbox --exclude shiguredo_nvcodec --exclude shiguredo_libvpx

  windows-binary:
    name: "Upload Binary for Windows"
    needs: [ci-windows]
    runs-on: windows-2022
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install packages to build external dependencies
        run: |
          choco install nasm -y
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          pip install meson ninja
      - name: Update PATH for nasm
        run: echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: rustup update stable
      - uses: shiguredo/github-actions/.github/actions/rust-cache@main
        with:
          os: windows-2022
          toolchain: stable

      - run: cargo build --release --no-default-features

      - name: Get the version
        id: get_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[] | select(.name == "hisui") | .version')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create archive
        shell: bash
        run: |
          mkdir -p hisui-${{ steps.get_version.outputs.version }}_windows-2022_x86_64
          cp target/release/hisui.exe hisui-${{ steps.get_version.outputs.version }}_windows-2022_x86_64/
          7z a hisui-${{ steps.get_version.outputs.version }}_windows-2022_x86_64.zip \
            hisui-${{ steps.get_version.outputs.version }}_windows-2022_x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: hisui-binary-windows-2022_x86_64
          path: hisui-${{ steps.get_version.outputs.version }}_windows-2022_x86_64.zip
