name: E2E Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/**
    paths-ignore:
      - "**.md"
      - "python/**"

jobs:
  e2e-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      OPENH264_VERSION: "2.6.0"
      OPENH264_PATH: ${{ github.workspace }}/libopenh264.so
      HISUI_E2E_CARGO_RUN_ARGS: --release
    steps:
      - uses: actions/checkout@v6
      - run: rustup update stable
      - name: Install packages to build external dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build nasm yasm build-essential autoconf automake libtool pkg-config cmake libx11-dev ffmpeg libfdk-aac-dev
      - uses: shiguredo/github-actions/.github/actions/rust-cache@main
        with:
          os: ubuntu-24.04
          toolchain: stable
      - name: Download libopenh264 v${{ env.OPENH264_VERSION }}
        run: |
          OPENH264_ARCHIVE="libopenh264-${OPENH264_VERSION}-linux64.8.so.bz2"
          OPENH264_URL="https://ciscobinary.openh264.org/${OPENH264_ARCHIVE}"
          echo "Downloading ${OPENH264_URL}"
          curl -fL -o "${OPENH264_ARCHIVE}" "${OPENH264_URL}"
          bzip2 -d "${OPENH264_ARCHIVE}"
          mv "libopenh264-${OPENH264_VERSION}-linux64.8.so" "${OPENH264_PATH}"
      - run: cargo build $HISUI_E2E_CARGO_RUN_ARGS
      - uses: astral-sh/setup-uv@v7
      - name: Run e2e tests
        env:
          HISUI_OPENH264_PATH: ${{ env.OPENH264_PATH }}
          HISUI_FDK_AAC_PATH: /usr/lib/x86_64-linux-gnu/libfdk-aac.so
        run: |
          uv sync
          uv run pytest -v
        working-directory: e2e-tests

  slack_notify:
    needs:
      - e2e-test
    permissions:
      actions: read
    timeout-minutes: 20
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Slack Notification
        uses: shiguredo/github-actions/.github/actions/slack-notify@main
        with:
          status: ${{ job.status }}
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_channel: hisui
          notify_mode: failure_and_fixed
        env:
          GH_TOKEN: ${{ github.token }}
