name: Pytest

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/**

env:
  CUDA_VERSION: 13.0.2

jobs:
  pytest:
    strategy:
      matrix:
        runs_on:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
        python_version:
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install packages to build external dependencies
        if: startsWith(matrix.runs_on, 'macos')
        run: |
          brew update
          brew install meson nasm yasm automake autoconf libtool

      - name: Install packages to build external dependencies
        if: startsWith(matrix.runs_on, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build nasm yasm build-essential autoconf automake libtool pkg-config yasm cmake

      - name: Convert Cargo version for Python
        uses: ./.github/actions/convert-cargo-version-for-python

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Sync uv dependencies
        run: uv sync

      - name: Build with Maturin
        run: uv run maturin develop --no-default-features

      - name: Run pytest
        run: uv run pytest
